services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=fdnZuQ4dKSb9
      - MYSQL_DATABASE=blog
      - MYSQL_USER=blog
      - MYSQL_PASSWORD=VNZkmjxTgLYf

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  db: